language: perl
sudo: false
cache: apt
addons:
  apt:
    packages:
    - git
    - g++
    - libdb-dev
    - libssl-dev
    - ncbi-blast+
    - mcl
    - fasttree
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
env:
  - PARALLEL_VERSION=20150522
  - PARALLEL_VERSION=20141022
  - PARALLEL_VERSION=20130922
install:
  - "source ./install_dependencies.sh"
script: "dzil test"
