language: perl
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
perl:
  - "5.10"
  - "5.14"
  - "5.20"
env:
  - PARALLEL_VERSION=20150522
  - PARALLEL_VERSION=20141022
  - PARALLEL_VERSION=20130922
install:
  - "source ./install_dependencies.sh"
script: "dzil test"
